### ISSUE TITLE
[BUG] Cannot use with flask-sqlalchemy v3.0.3

### ISSUE THREAD

**Issue by NiNiyas** [christopherpickering/flask-session2#25]
## System Info
 - OS: Windows 10
 - Python Version: 3.11.1

## Issue
Hi!

I just updated flask-sqlalchemy to v3.0.3 version and I cannot use it with flask-session2 v1.3.1. Runs into `RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.`

https://github.com/pallets-eco/flask-sqlalchemy/pull/1151

I was able to fix this using the following code snippet:

``` python
def init_app(self, app, db=None):
        """This is used to set up session for your app object.

        When app.session_interface is None
        or
        app.config['SESSION_TYPE'] == 'custom'
        we using custom implementation from application.

        :param app: the Flask app object with proper configuration.
        """
        if app.session_interface is None or (
            "SESSION_TYPE" in app.config and app.config["SESSION_TYPE"] != "custom"
        ):
            app.session_interface = self._get_interface(app, db)

def _get_interface(self, app, db):
....
....
elif config["SESSION_TYPE"] == "sqlalchemy":
            session_interface = SqlAlchemySessionInterface(
                app,
                db,
                config["SESSION_SQLALCHEMY_TABLE"],
                config["SESSION_KEY_PREFIX"],
                config["SESSION_USE_SIGNER"],
                config["SESSION_PERMANENT"],
                config["SESSION_SQLALCHEMY_SEQUENCE"],
                config["SESSION_AUTODELETE"],
```

and initialize with `sess.init_app(app, db)`

## How To Reproduce
- Update flask-sqlalchemy to v3.0.3
- Try initializing a session.

**Comment by rayanth** [comment]
this particular error is resolved by adding in your application config, `SESSION_SQLALCHEMY = db` (where `db` is the initialized database instance from `db = SQLALchemy()`)

**Comment by NiNiyas** [comment]
Thank you. Im just dumb.

**Comment by christopherpickering** [comment]
Delete it this per @NiNiyas request. Thanks for helping @rayanth .
